name: Create artifact [MAC]

on: 
  workflow_dispatch: {}

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: npm install & build
        run: |
          npm ci
          npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: macos-build
          retention-days: 3
          path: |
            build
            !build/*-unpacked
            !build/.icon-ico
